from .pysssss import init

if init(check_imports=["onnxruntime", "huggingface_hub"]):
    from .wd14tagger import NODE_CLASS_MAPPINGS as WD14_NODE_CLASS_MAPPINGS
    from .wd14tagger import NODE_DISPLAY_NAME_MAPPINGS as WD14_NODE_DISPLAY_NAME_MAPPINGS
    from .booru_tagger import NODE_CLASS_MAPPINGS as BOORU_NODE_CLASS_MAPPINGS
    from .booru_tagger import NODE_DISPLAY_NAME_MAPPINGS as BOORU_NODE_DISPLAY_NAME_MAPPINGS

    NODE_CLASS_MAPPINGS = {}
    NODE_CLASS_MAPPINGS.update(WD14_NODE_CLASS_MAPPINGS)
    NODE_CLASS_MAPPINGS.update(BOORU_NODE_CLASS_MAPPINGS)

    NODE_DISPLAY_NAME_MAPPINGS = {}
    NODE_DISPLAY_NAME_MAPPINGS.update(WD14_NODE_DISPLAY_NAME_MAPPINGS)
    NODE_DISPLAY_NAME_MAPPINGS.update(BOORU_NODE_DISPLAY_NAME_MAPPINGS)

    WEB_DIRECTORY = "./web"
    __all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
